#!/bin/bash

        echo "Enter the path of the directory: "
        read directory
if [ -d "$directory" ]
then
        echo "Directory exist!!"
else
        mkdir -p "$directory"
	echo "Directory created!!"
fi
