#!/bin/bash
echo "Enter the path of the directory: "
read directory
if [ -d $directory ]
then
echo "Directory exists!!"
mkdir -p "$directory"/{Monday,Tuesday,Wednesday,Thursday,Friday}
tree $directory
echo "Directory and sub directories created!!"
else
echo "No such directory found!!"
mkdir -p "$directory"/{Monday,Tuesday,Wednesday,Thursday,Friday}
echo
tree $directory
echo
echo "Directory and sub directories created!!"
fi
